name: Output info
on:
  push:
    branches:
      - dev
  pull_request:
    types: [opened, synchronize, reopened, closed]
    branches:
      - dev
jobs:
  output-info:
    runs-on: ubuntu-latest
    steps:
      - name: Get head_ref
        run: echo "${{ github.head_ref }}"
      - name: Get ref_name
        run: echo "${{ github.ref_name }}"
      #- name: Output event details
      # run: echo "${{ toJSON(github.event) }}"
