name: Output info
on:
  push:
    branches:
      - dev
  pull_request:
    types: [opened, synchronize, reopened, closed]
    branches:
      - dev
jobs:
  set-env:
    runs-on: ubuntu-latest
    outputs:
      deployment-environment: ${{ env.type }}
    steps:
      - name: Set env variable
        run: |
          if [ ${{ github.ref_name }} == 'dev' ] || [ ${{ github.ref_name }} == f-* ]; then
            echo "{type}='dev'" >> $GITHUB_ENV
          elif [ ${{ github.ref_name }} == 'master' ]; then
            echo "{type}='prod'" >> $GITHUB_ENV
          else
            echo "{type}='dev'" >> $GITHUB_ENV
          fi
        shell: bash
  output-info:
    needs: set-env
    runs-on: ubuntu-latest
    environment: ${{ needs.set-env.outputs.deployment-environment }}
    steps:
      - name: Get env type
        run: echo "${{ env.ENV }}"
      #- name: Get head_ref
      #  run: echo "${{ github.head_ref }}"
      #- name: Get ref_name
      #  run: echo "${{ github.ref_name }}"
      #- name: Output event details
      # run: echo "${{ toJSON(github.event) }}"
